import { useState } from 'react';
import { AnimatePresence } from 'framer-motion';
import AddressSearch from '../components/analysis/AddressSearch';
import ReportPanel from '../components/analysis/ReportPanel';
import { fetchPlutoData } from '../api/geosearch';
import { calcSpatialScore, calcDaylightScore, calcEfficiencyScore } from '../scoring/engine';

function useBuilding() {
  const [pluto, setPluto] = useState(null);
  const [scores, setScores] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const load = async (item) => {
    setPluto(null); setScores(null); setError(null);
    if (!item.bbl) { setError('No PLUTO data found for this parcel. Try a nearby address or check the BBL.'); return; }
    setLoading(true);
    try {
      const data = await fetchPlutoData(item.bbl);
      if (!data) { setError('No PLUTO data found for this parcel. Try a nearby address or check the BBL.'); setLoading(false); return; }
      setPluto(data);
      setScores({
        spatial: calcSpatialScore(data),
        daylight: calcDaylightScore(data),
        efficiency: calcEfficiencyScore(data),
      });
    } catch {
      setError('Data temporarily unavailable. Please try again.');
    } finally { setLoading(false); }
  };

  return { pluto, scores, loading, error, load };
}

function LoadingIndicator() {
  return (
    <div className="flex items-center gap-3 py-8 justify-center">
      <div className="w-5 h-5 border-2 rounded-full animate-spin" style={{ borderColor: '#d6d0c4', borderTopColor: '#1A4D2E' }} />
      <span className="text-sm font-medium" style={{ color: '#1A4D2E' }}>Loading building data...</span>
    </div>
  );
}

function ErrorMsg({ msg }) {
  if (!msg) return null;
  return <div className="rounded-lg border px-5 py-4 text-sm" style={{ background: '#fdf2f2', borderColor: '#f5c6c6', color: '#C0392B' }}>{msg}</div>;
}

export default function NewAnalysis() {
  const [comparing, setComparing] = useState(false);
  const a = useBuilding();
  const b = useBuilding();

  return (
    <div className={`${comparing ? 'max-w-6xl' : 'max-w-3xl'} mx-auto`}>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold" style={{ color: '#1A4D2E' }}>New Analysis</h1>
          <p className="text-sm" style={{ color: '#6b7c6e' }}>
            {comparing
              ? 'Compare two NYC buildings side by side.'
              : 'Enter an NYC address to generate a spatial feasibility report.'}
          </p>
        </div>
        <button
          onClick={() => setComparing(!comparing)}
          className="px-4 py-2 rounded-lg text-sm font-medium transition-all"
          style={{
            background: comparing ? '#1A4D2E' : '#f0f7f1',
            color: comparing ? '#faf9f6' : '#1A4D2E',
            border: '1px solid #1A4D2E',
          }}
        >
          {comparing ? '✕ Exit Compare' : '⇄ Compare Two'}
        </button>
      </div>

      {!comparing ? (
        /* Single building mode */
        <div>
          <div className="mb-6"><AddressSearch onSelect={a.load} /></div>
          {a.loading && <LoadingIndicator />}
          <ErrorMsg msg={!a.loading ? a.error : null} />
          <AnimatePresence>
            {a.pluto && a.scores && !a.loading && <ReportPanel pluto={a.pluto} scores={a.scores} />}
          </AnimatePresence>
          {a.pluto && a.scores && !a.loading && (
            <p className="text-xs leading-relaxed pb-4 mt-6" style={{ color: '#94a3b8' }}>
              This report is generated by Plenum's spatial analysis engine using NYC PLUTO data and is intended
              for preliminary screening only. © 2026 Plenum Technologies
            </p>
          )}
        </div>
      ) : (
        /* Side-by-side comparison mode */
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {[{ bld: a, label: 'Building A' }, { bld: b, label: 'Building B' }].map(({ bld, label }) => (
            <div key={label}>
              <p className="text-xs font-semibold mb-2 uppercase tracking-wide" style={{ color: '#6b7c6e' }}>{label}</p>
              <div className="mb-4"><AddressSearch onSelect={bld.load} /></div>
              {bld.loading && <LoadingIndicator />}
              <ErrorMsg msg={!bld.loading ? bld.error : null} />
              <AnimatePresence>
                {bld.pluto && bld.scores && !bld.loading && <ReportPanel pluto={bld.pluto} scores={bld.scores} compact />}
              </AnimatePresence>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
